const $ = (selector) => document.querySelector(selector);

function setupMenu() {
  let button = $('.menu-toggle'); const nav = $('#main-nav');
  if (!nav) return;
  if (!button) { button = document.createElement('button'); button.className = 'menu-toggle'; button.type = 'button'; button.setAttribute('aria-expanded', 'false'); button.setAttribute('aria-controls', 'main-nav'); button.textContent = '[ MENÚ ]'; nav.before(button); }
  button.addEventListener('click', () => { const open = nav.classList.toggle('open'); button.setAttribute('aria-expanded', open); button.textContent = open ? '[ CERRAR ]' : '[ MENÚ ]'; });
  nav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => nav.classList.remove('open')));
}
function escapeHTML(value = '') { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function projectCard(project, number) { return `<article class="project panel"><span class="corner corner-tl">+</span><span class="corner corner-tr">+</span><span class="corner corner-bl">+</span><span class="corner corner-br">+</span><div class="project-top"><span>${String(number).padStart(2, '0')} / ${escapeHTML(project.category)}</span><span>${new Date(project.date).getFullYear()}</span></div><div class="project-art"><b>${escapeHTML(project.badge || 'SEC')}</b></div><h3>${escapeHTML(project.title)}</h3><p>${escapeHTML(project.summary)}</p><a href="proyecto.html?id=${encodeURIComponent(project.id)}">[ LEER ARTÍCULO → ]</a></article>`; }
async function getProjects() { const response = await fetch('data/projects.json'); if (!response.ok) throw new Error('No se pudieron cargar los proyectos'); const projects = await response.json(); return projects.sort((a, b) => new Date(b.date) - new Date(a.date)); }
async function renderHome() { const target = $('#latest-projects'); if (!target) return; try { const projects = await getProjects(); $('#project-count').textContent = `(${String(projects.length).padStart(2, '0')})`; target.innerHTML = projects.slice(0, 3).map((project, index) => projectCard(project, index + 1)).join('') || '<p>Aún no hay proyectos publicados.</p>'; } catch { target.innerHTML = '<p>No fue posible cargar los proyectos.</p>'; } }
async function renderProjectList() { const target = $('#all-projects'); if (!target) return; try { const projects = await getProjects(); $('#project-count').textContent = `(${String(projects.length).padStart(2, '0')})`; target.innerHTML = projects.map((project, index) => projectCard(project, index + 1)).join('') || '<p>Aún no hay proyectos publicados.</p>'; } catch { target.innerHTML = '<p>No fue posible cargar los proyectos.</p>'; } }
async function renderArticle() { const target = $('#project-article'); if (!target) return; const id = new URLSearchParams(location.search).get('id'); try { const project = (await getProjects()).find((item) => item.id === id); if (!project) throw new Error(); document.title = `${project.title} — Lucas Security`; target.innerHTML = `<p class="eyebrow">// ${escapeHTML(project.category)} · ${new Date(project.date).getFullYear()}</p><h1>${escapeHTML(project.title)}</h1><p class="article-lead">${escapeHTML(project.summary)}</p><div class="article-content">${escapeHTML(project.content).replace(/\n/g, '<br>')}</div><a class="button" href="proyectos.html">[ ← VOLVER A PROYECTOS ]</a>`; } catch { target.innerHTML = '<h1>Proyecto no encontrado</h1><a class="button" href="proyectos.html">[ ← VOLVER ]</a>'; } }
setupMenu(); renderHome(); renderProjectList(); renderArticle();
